#!/bin/bash
# Primary metric: mean device-reported decode tps over the frozen primary
# prompt set, measured through the real request path on the attached board.
#
# Env knobs (never change what the metric means):
#   AUTO_GROUPS=primary,...   restrict groups (diagnostics only; default all)
#   AUTO_SAVE=1               rewrite the device golden (only for a documented
#                             re-baseline, never to make a run look good)
#   AUTO_PROFILE=1            build with ND_PROFILE=ON for the phase breakdown
#                             (adds timers: do not use for keep/discard)
#   AUTO_NOFLASH=1            re-measure the already-flashed app (noise checks)
#   AUTO_MODEL=1              also rewrite the model partition
set -euo pipefail
cd "$(dirname "$0")/.."
AUTO_LOG_DIR=${AUTO_LOG_DIR:-$PWD/.auto/runs/local}
mkdir -p "$AUTO_LOG_DIR"
ROOT=$PWD

# Refuse the failure mode that consumed runs #302-#329: measuring the exact
# same shipping tree because the autoresearch iteration driver demands a
# number.  Prompt text is not strong enough to stop that loop, so enforce it
# before acquiring a board or building anything.
#
# The signature covers tracked/untracked runtime inputs plus the resolved IDF
# sdkconfig (which is intentionally gitignored).  Build products are ignored by
# git and therefore absent.  A successful full measurement records its
# signature.  One explicit confirmation is available for a genuinely new
# candidate, but it requires a reason and is then exhausted for that signature.
shipping_signature() {
    {
        git ls-files -co --exclude-standard -z -- engine esp32 host tools model |
            sort -z |
            while IFS= read -r -d '' f; do
                if [ -f "$f" ]; then sha256sum "$f"; fi
            done
        if [ -f esp32/sdkconfig ]; then sha256sum esp32/sdkconfig; fi
        true
    } | sha256sum | cut -d' ' -f1
}

SIG_HISTORY="$AUTO_LOG_DIR/measured_shipping_signatures"
REPEAT_HISTORY="$AUTO_LOG_DIR/measured_repeat_overrides"
CURRENT_SHIPPING_SIG=$(shipping_signature)
# The `true` inside the group above is load-bearing, not decoration: measure.sh
# runs under `set -euo pipefail`, and on a freshly synced checkout esp32/sdkconfig
# does not exist yet (it is generated by the build and is gitignored), so the old
# `[ -f esp32/sdkconfig ] && sha256sum ...` made the whole pipeline fail and killed
# the run before it printed a single byte. Four board lanes died that way on
# 2026-09-22 with rc=1 and empty logs, which looked exactly like a dead launcher.
# Strict-harness equivalence: the run_experiment guard accepts only the literal
# `bash .auto/measure.sh`, so a diagnostic run cannot carry AUTO_* env vars. A
# marker file supplies the same two values a stated repeat needs. This does NOT
# weaken the anti-repeat guard: a repeat still requires a non-empty reason, and the
# signature + timestamp + reason are still appended to $REPEAT_HISTORY below. The
# marker file is deleted when the diagnostic is over.
if [ -f "$AUTO_LOG_DIR/diag_repeat_ok" ]; then
    REPEAT_MARKER="$AUTO_LOG_DIR/diag_repeat_ok"
elif [ -f .auto/diag_repeat_ok ]; then
    # Second location, and the reason it exists: AUTO_LOG_DIR is $PWD/.auto/runs/local, so an
    # operator who reads the documented knob name and writes .auto/diag_repeat_ok gets silence.
    # That is exactly what happened on 2026-09-23 - the marker was written three times and the
    # guard refused every time, so the switch had never once executed its own purpose. `-s` not
    # `-f` below, so an empty marker can never authorise a repeat without a reason.
    REPEAT_MARKER=".auto/diag_repeat_ok"
else
    REPEAT_MARKER=""
fi
if [ -n "$REPEAT_MARKER" ] && [ -s "$REPEAT_MARKER" ] && [ -z "${AUTO_ALLOW_REPEAT:-}" ]; then
    AUTO_ALLOW_REPEAT=1
    AUTO_REPEAT_REASON=$(cat "$REPEAT_MARKER")
    export AUTO_ALLOW_REPEAT AUTO_REPEAT_REASON
fi
# PROVENANCE, printed by the runner itself rather than by a wrapper that could be
# lying: a `needle-board run N -- cmd` pane executes in worker N's checkout, so a
# lane can silently build a tree nobody intended (measured: a "fusion" gate run on
# board 1 reported decode 5.1167 because its worker still held the run #391-era
# fw3fold engine, engine_md5=01c1638ef34c). Set EXPECT_ENGINE_MD5 and the run
# refuses to start on a mismatch instead of reporting a number for the wrong code.
PROV_TREE=$(pwd)
PROV_HEAD=$(git rev-parse --short HEAD 2>/dev/null || echo none)
PROV_ENGINE=$(md5sum engine/src/nd_quant.c 2>/dev/null | cut -d" " -f1)
echo "PROVENANCE tree=${PROV_TREE} head=${PROV_HEAD} engine_md5=${PROV_ENGINE}"
# Prefix match on purpose: a 12-hex md5 prefix is what every ledger line quotes, and
# requiring the full 32 characters made lanes abort on a correct tree (measured: three
# lanes exited with PROVENANCE_MISMATCH while printing the expected 12-hex value).
PROV_BAD=0
if [ -n "${EXPECT_ENGINE_MD5:-}" ]; then
    case "${PROV_ENGINE}" in
        ${EXPECT_ENGINE_MD5}*) : ;;
        *) PROV_BAD=1 ;;
    esac
fi
if [ "${PROV_BAD}" = 1 ]; then
    echo "PROVENANCE_MISMATCH want=${EXPECT_ENGINE_MD5} have=${PROV_ENGINE} tree=${PROV_TREE}"
    exit 3
fi
SIGNATURE_SEEN=0
grep -q "^${CURRENT_SHIPPING_SIG} " "$SIG_HISTORY" 2>/dev/null && SIGNATURE_SEEN=1
if [ "$SIGNATURE_SEEN" = 1 ]; then
    if [ "${AUTO_ALLOW_REPEAT:-0}" != 1 ]; then
        echo "UNCHANGED_SHIPPING_IMAGE_REFUSED signature=${CURRENT_SHIPPING_SIG}"
        echo "Implement a real candidate first. Controls belong in concurrent candidate batches."
        exit 42
    fi
    if [ -z "${AUTO_REPEAT_REASON:-}" ]; then
        echo "REPEAT_REASON_REQUIRED: set AUTO_REPEAT_REASON for the one allowed confirmation"
        exit 43
    fi
    if grep -q "^${CURRENT_SHIPPING_SIG} " "$REPEAT_HISTORY" 2>/dev/null; then
        echo "REPEAT_BUDGET_EXHAUSTED signature=${CURRENT_SHIPPING_SIG}"
        echo "This image already has its confirmation; implement the next candidate."
        exit 44
    fi
    echo "EXPLICIT_REPEAT_ALLOWED signature=${CURRENT_SHIPPING_SIG} reason=${AUTO_REPEAT_REASON}"
fi

# The coordinator's normal confirmation run shares board 1 with its worker.
# Pool workers already hold this lock in needle-board.
if [ -z "${NEEDLE_BOARD:-}" ] && [ -d /root/board-pool ]; then
    exec 9>/root/board-pool/locks/board1.lock
    flock -n 9 || { echo "Board 1 is busy"; exit 1; }
    FLASH_PORT=/dev/needle-pi/flash
    SERIAL_PORT=/dev/needle-pi/console
fi
# IDF_PATH can be exported while the tools are not on PATH (the experiment
# harness does this); sourcing is then what makes idf.py/esptool findable.
if ! command -v idf.py >/dev/null 2>&1; then
    . /opt/esp/idf/export.sh >/dev/null 2>&1 || true
fi
FLASH_PORT=${FLASH_PORT:-/dev/ttyACM0}
SERIAL_PORT=${SERIAL_PORT:-/dev/ttyACM1}

# Fast pre-check: the engine has to compile at all (seconds, no hardware).
cmake -S host -B host/build > "$AUTO_LOG_DIR/auto_host.log" 2>&1
cmake --build host/build -j8 >> "$AUTO_LOG_DIR/auto_host.log" 2>&1 || {
    echo HOST_BUILD_FAILED; grep -E 'error' "$AUTO_LOG_DIR/auto_host.log" | head -20; exit 1; }
.venv/bin/python tools/download_model.py --verify-only > /dev/null

CFG=(-DNEEDLE_PROFILE=OFF)
[ "${AUTO_PROFILE:-0}" = 1 ] && CFG=(-DNEEDLE_PROFILE=ON)
t0=$(date +%s)
idf.py -C esp32 ${CFG[@]+"${CFG[@]}"} build > "$AUTO_LOG_DIR/auto_build.log" 2>&1 || {
    echo FIRMWARE_BUILD_FAILED
    grep -E 'error:|ERROR' "$AUTO_LOG_DIR/auto_build.log" | head -25
    exit 1; }
echo "build_s=$(( $(date +%s) - t0 ))"
# A rebuild that silently no-ops is the one failure mode that makes every number
# below meaningless: it measures the previous candidate. Record what went in.
{ echo "engine_md5=$(md5sum engine/src/*.c engine/include/*.h | md5sum | cut -c1-12)"
  echo "app_md5=$(md5sum esp32/build/needle_demo.bin | cut -c1-12)"; } > "$AUTO_LOG_DIR/auto_build_id.txt"
cat "$AUTO_LOG_DIR/auto_build_id.txt"

if [ "${AUTO_NOFLASH:-0}" != 1 ]; then
    t0=$(date +%s)
    if [ "${AUTO_MODEL:-0}" = 1 ]; then
        python3 -m esptool --chip esp32s3 --port "$FLASH_PORT" \
            --baud 921600 write_flash 0x210000 model/needle3.cact > "$AUTO_LOG_DIR/auto_model.log" 2>&1
    fi
    idf.py -C esp32 -p "$FLASH_PORT" flash > "$AUTO_LOG_DIR/auto_flash.log" 2>&1 || {
        echo FLASH_FAILED; tail -20 "$AUTO_LOG_DIR/auto_flash.log"; exit 1; }
    echo "flash_s=$(( $(date +%s) - t0 ))"
fi

# Loud, non-fatal. Another worker's source or build config being out of sync does
# not invalidate THIS canonical measurement, but it invalidates the next three-board
# batch, and the failure mode - a control reading low because its worker is stale -
# looks exactly like a result. Run #300 found all three workers behind HEAD and two
# of them with run #293's assertion-level change still baked into their
# sdkconfig.defaults. The check itself is falsifiable (SELFTEST=1).
bash .auto/board_config_check.sh > "$AUTO_LOG_DIR/auto_config_check.log" 2>&1 ||
    echo "CONFIG_DRIFT_WARN: $(tail -1 "$AUTO_LOG_DIR/auto_config_check.log")"

ARGS=(device --port "$SERIAL_PORT")
[ -n "${AUTO_GROUPS:-}" ] && ARGS+=(--groups "$AUTO_GROUPS")
# The baseline run (iteration 1) freezes the device goldens; later runs compare
# against them and must stay byte-exact. AUTO_SAVE=1 is the documented re-baseline
# escape hatch and has to actually reach bench.py - it used to be read by the header
# comment only, which left the device golden un-updateable forever and any added
# held-out case comparing against nothing. bench.py still refuses a partial save.
SAVE=0
[ "$(wc -l < .auto/log.jsonl 2>/dev/null || echo 0)" -le 1 ] && SAVE=1
[ -n "${AUTO_SAVE:-}" ] && SAVE=1
cd "$ROOT"
BENCH_LOG="$AUTO_LOG_DIR/auto_bench.log"
if [ "$SAVE" = 1 ]; then
    .venv/bin/python .auto/bench.py "${ARGS[@]}" --save-golden 2>&1 | tee "$BENCH_LOG"
else
    .venv/bin/python .auto/bench.py "${ARGS[@]}" 2>&1 | tee "$BENCH_LOG"
fi

# Device byte-exactness is a hard gate, not a number to eyeball. checks.sh's only
# byte-exact veto runs on the HOST build, where nd_parallel_rows is rows_serial -
# so a two-core defect is invisible there by construction (that is exactly how
# run #159's shared-table race looked byte-exact) and can only be caught here.
# Skipped for a restricted AUTO_GROUPS run, which does not measure the whole set.
# grep failures are neutralised because `set -e` would otherwise exit on a short
# run where a metric line simply is not present.
if [ -z "${AUTO_GROUPS:-}" ]; then
    EX=$(grep -o 'device_output_exact=[0-9]*' "$BENCH_LOG" | tail -1 | cut -d= -f2 || true)
    CS=$(grep -o 'device_cases=[0-9]*' "$BENCH_LOG" | tail -1 | cut -d= -f2 || true)
    MISS=$(grep -o 'device_golden_missing=[0-9]*' "$BENCH_LOG" | tail -1 | cut -d= -f2 || true)
    [ "${EX:-0}" = "${CS:-1}" ] || { echo "DEVICE_OUTPUT_DIVERGED ${EX:-0}/${CS:-?}"; exit 1; }
    # exact == cases is satisfiable while comparing against nothing (run #296).
    # A documented re-baseline (AUTO_SAVE=1) is the one run whose purpose is to ADD
    # golden entries, so requiring missing == 0 there would make the suite
    # un-widenable - the clause that made #296's save work is the same clause. The
    # byte-exact clause above still runs, and the skip is printed rather than
    # silent: the next (non-save) run is gated on missing == 0 again.
    if [ "$SAVE" = 1 ]; then
        echo "DEVICE_GATE_PARTIAL save-run exact=${EX}/${CS} new_entries=${MISS:-?}"
    else
        [ "${MISS:-1}" = "0" ] || { echo "DEVICE_GOLDEN_INCOMPLETE missing=${MISS:-?}"; exit 1; }
        echo "DEVICE_GATE_OK exact=${EX}/${CS} golden_missing=${MISS}"
    fi
fi

# Record only after the benchmark and hard device gate complete. Recompute so a
# deleted/regenerated sdkconfig is represented by the configuration actually
# measured, not by the pre-build filesystem state.
MEASURED_SHIPPING_SIG=$(shipping_signature)
if ! grep -q "^${MEASURED_SHIPPING_SIG} " "$SIG_HISTORY" 2>/dev/null; then
    printf '%s %s %s\n' "$MEASURED_SHIPPING_SIG" "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$(git rev-parse --short HEAD)" >> "$SIG_HISTORY"
fi
if [ "$SIGNATURE_SEEN" = 1 ] && [ "${AUTO_ALLOW_REPEAT:-0}" = 1 ]; then
    printf '%s %s %s\n' "$MEASURED_SHIPPING_SIG" "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$AUTO_REPEAT_REASON" >> "$REPEAT_HISTORY"
fi
