#!/usr/bin/env python3
"""Candidate `bundle78` = accepted + `asmemo` (+2.200 %) + `fusion-r5` (+0.660 %), installed as one change.

Generated by `.auto/exp78/make_bundle.py`, which composes the two already-verified candidate scripts on
the accepted tree rather than hand-writing a third implementation. Both halves keep their own guards:
`.auto/exp77/test_asmemo.c` includes the installed `nd_quant.c` and exercises the memoised predicate,
and the transform side is the same fused body that has been proven bit-exact against the exported
`nd_fwht` over 1,472,640 comparisons plus the odd-split guard.

Why the bundle is a measurement and not a formality: the two mechanisms are independent - one removes
a 130,560-read per-token walk in the 2-bit projection wrapper, the other fuses butterfly stages and
moves the field-dead transform fallbacks out of IRAM - but they meet in the same file and they pull on
the same scarce resource from opposite directions (the fusion's kernel text is subtracted from internal
heap, the memo's 960 B table is too). #431 measured a bundle delivering MORE than the sum of its parts,
so the composed result is genuinely unknown here, and each half is above the bar by itself, so the
interesting question is whether the bundle is >= +2.86 % or less than the better half.
"""
import hashlib
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
BASES = {"nd_quant.c": "a485999e5c91", "nd_model.c": "0d639424f636", "nd_quant.h": "57a0fa8af900"}
TARGETS = {"nd_quant.c": "engine/src/nd_quant.c",
           "nd_model.c": "engine/src/nd_model.c",
           "nd_quant.h": "engine/include/nd_quant.h"}


def main() -> int:
    target = sys.argv[1] if len(sys.argv) > 1 else "engine/src/nd_quant.c"
    root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(target))))
    data = {}
    for key, rel in TARGETS.items():
        path = os.path.join(root, rel)
        blob = open(path, "rb").read()
        if hashlib.md5(blob).hexdigest()[:12] != BASES[key]:
            print(f"BASE_MISMATCH {rel} got={hashlib.md5(blob).hexdigest()[:12]} want={BASES[key]}")
            return 2
        new = open(os.path.join(HERE, key + ".bundle"), "rb").read()
        text = new.decode()
        if key == "nd_quant.c" and (text.count("nd_fwht4s") < 2 or text.count("s_asm_memo") != 3
                                    or "s_asm_blob" in text
                                    or text.count("gemv4_asm_usable") != 3 or "ctx.base = 0" not in text):
            print(f"CONTENT_ASSERT_FAILED {key}")
            return 3
        if key == "nd_quant.h" and text.count("nd_cq_asmemo_reset") != 1:
            print("CONTENT_ASSERT_FAILED header")
            return 3
        if key == "nd_model.c" and text.count("nd_cq_asmemo_reset();") != 1:
            print("CONTENT_ASSERT_FAILED close")
            return 3
        data[path] = new
    for path, blob in data.items():
        open(path, "wb").write(blob)
        print("PATCHED " + path + " md5=" + hashlib.md5(blob).hexdigest()[:12])
    print("APPLIED bundle78 root=" + root)
    return 0


if __name__ == "__main__":
    sys.exit(main())
