set -g default-terminal 'tmux-256color'
set -ga terminal-overrides ',xterm-256color:Tc'
set -g history-limit 50000
set -g mouse on
set -s escape-time 10
set -s extended-keys on
set -as terminal-features ',xterm*:extkeys'
set -g status-right 'Detach: Ctrl-b d | %H:%M'
set -g renumber-windows on
