#!/usr/bin/env python3
"""Experiment 36 lane 3 - unroll `kv_store_int8` four elements at a time.

GENERATED, not typed. The shipped per-element body is extracted from
engine/src/nd_model.c and instantiated four times with mechanical substitutions.
This function's Markstein residual is exactly what makes it bit-identical to
`x / scale`, so a hand transcription could differ in a value range the frozen
prompts never reach - run #230's nd_expf class, which every golden waved through.
The extraction is asserted: if the loop's shape changes, this fails loudly instead
of quietly shipping something else.

Guard, residual and fixup are independent per element, so grouping four stores
identical int8 values. The odd tail is the shipped body verbatim.
"""
import pathlib
import re

SRC = pathlib.Path("engine/src/nd_model.c")
body = SRC.read_text()

HEAD = "    const float r = 1.0f / scale;\n    uint32_t  i;\n"
assert body.count(HEAD) == 1, "kv_store_int8 preamble changed"

loop_open = body.index("    for (i = 0; i < n; i++) {", body.index(HEAD))
loop_close = body.index("\n    }\n", loop_open) + len("\n    }\n")
inner = body[loop_open:loop_close][body[loop_open:loop_close].index("{") + 1:]
inner = inner[:inner.rindex("\n    }")] or inner

# Re-extract precisely: everything between the loop's braces.
loop_text = body[loop_open:loop_close]
first_brace = loop_text.index("{")
inner = loop_text[first_brace + 1:loop_text.rindex("}")].rstrip()
assert "(int8_t)lrintf(q)" in inner, "unexpected loop body"

def inst(k: int) -> str:
    """One element's body, reading src[i+k] and writing dst[i+k]."""
    t = inner.replace("src[i]", f"src[i + {k}u]").replace("dst[i]", f"dst[i + {k}u]")
    if k:
        for name in ("x", "q", "e"):
            t = re.sub(rf"\b{name}\b(?![_\w])", f"{name}{k}", t)
    return t

DOC = """    /* Unrolled by 4. GENERATED by .auto/exp36/make_kvvariant.py: the shipped
     * element body is extracted and instantiated four times, because the
     * Markstein residual is what makes this bit-identical to `x / scale` and a
     * hand-typed copy could differ in a range the frozen prompts never reach
     * (#230's nd_expf class). Guard, residual and fixup are independent per
     * element, so every stored int8 - and every lrintf - is unchanged. */
"""

unrolled = (DOC
            + "    for (; i + 3u < n; i += 4u) {\n"
            + "\n".join(inst(k) for k in range(4)) + "\n    }\n"
            + "    for (; i < n; i++) {" + inner + "\n    }\n")

out = (body[:body.index(HEAD)]
       + HEAD.replace("    uint32_t  i;\n", "    uint32_t  i = 0;\n")
       + body[body.index(HEAD) + len(HEAD):loop_open]
       + unrolled + body[loop_close:])

assert out.count("lrintf(") == 5, "unroll shape wrong"   # tail + four instances
pathlib.Path("/tmp/ndm_kvstore.c").write_text(out)
print("wrote /tmp/ndm_kvstore.c")
print("shipped first statement:", inner.strip().splitlines()[0].strip()[:56])
